PMTGroup3/PMT.Presentation/Controllers/AirportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PMT.Presentation.Models;
using PMT.DataAccess;
namespace PMT.Presentation.Controllers
{

    public class AirportController : Controller
    {
        public ActionResult GetAirport()
        {
            if (Session["role"] != null)
            {
                if ((string)Session["role"] == "admin")
                {
                    Repository r = new Repository();
                    List<Airport> airports = r.GetAirportDetails();
                    List<AirportModel> result = new List<AirportModel>();
                    foreach (Airport a in airports)
                    {
                        AirportModel model = new AirportModel();
                        model.AirportCode = a.AirportCode;
                        model.AirportName = a.AirportName;
                        model.Description = a.Description;
                        model.Location = a.Location;
                        result.Add(model);
                    }
                    return View(result);
                }
            }
            return RedirectToAction("Login","User");
        }

        public ActionResult Create()
        {
            if (Session["role"] != null)
            {
                if ((string)Session["role"] == "admin")
                {
                    Models.AirportModel model = new Models.AirportModel();
                    return View(model);
                }
            }
            return RedirectToAction("Login", "User");
        }
        [HttpPost]
        public ActionResult Create(AirportModel model)
        {
            if (Session["role"] != null)
            {
                if ((string)Session["role"] == "admin")
                {
                    Repository r = new Repository();
                    Airport result = new Airport();
                    result.AirportCode = model.AirportCode;
                    result.AirportName = model.AirportName;
                    result.Description = model.Description;
                    result.Location = model.Location;
                    int output = 0;
                    if (ModelState.IsValid)
                    {
                        output = r.AddAirport(result);
                        if (output == 1)
                        {
                            ViewBag.AddMessage = "airport details added !!";
                        }
                        else
                        {
                            ViewBag.AddError = "Not added !!";
                        }
                    }
                    return View();
                }
            }
            return RedirectToAction("Login", "User");
        }
        public ActionResult UpdateAirport(String id)
        {
            if (Session["role"] != null)
            {
                if ((string)Session["role"] == "admin")
                {
                    Repository r = new Repository();
                    Airport a = r.GetAirport(id);
                    AirportModel model = new AirportModel();
                    model.AirportCode = a.AirportCode;
                    model.AirportName = a.AirportName;
                    model.Description = a.Description;
                    model.Location = a.Location;
                    return View(model);
                }
            }
            return RedirectToAction("Login", "User");
        }
        [HttpPost]
        public ActionResult UpdateAirport(AirportModel a)
        {
            if (Session["role"] != null)
            {
                if ((string)Session["role"] == "admin")
                {
                    Repository r = new Repository();
                    Airport updateAirport = new Airport();
                    updateAirport.AirportCode = a.AirportCode;
                    updateAirport.AirportName = a.AirportName;
                    updateAirport.Description = a.Description;
                    updateAirport.Location = a.Location;
                    int result = 0;
                    if (ModelState.IsValid)
                    {
                        result = r.UpdateAirport(updateAirport);
                        if (result == 1)
                        {
                            ViewBag.UpdateMessage = "airport details updated !!";
                        }
                        else
                        {
                            ViewBag.UpdateError = "not updated !!!";
                        }
                    }
                    return View();
                }
            }
            return RedirectToAction("Login", "User");
        }




        public ActionResult RemoveAirport(String AirportCode)
        {
            if (Session["role"] != null)
            {
                if ((string)Session["role"] == "admin")
                {
                    Repository r = new Repository();
                    Airport ap = r.GetAirport(AirportCode);
                    AirportModel model = new AirportModel();
                    model.AirportCode = ap.AirportCode;
                    model.AirportName = ap.AirportName;
                    model.Location = ap.Location;
                    model.Description = ap.Description;
                    return View(model);
                }
            }
            return RedirectToAction("Login", "User");
        }
        [HttpPost] 
        [ActionName("RemoveAirport")]
        public ActionResult Remove(String AirportCode)
        {
            if (Session["role"] != null)
            {
                if ((string)Session["role"] == "admin")
                {
                    Repository r = new Repository();
                    int result = 0;
                    if (ModelState.IsValid)
                    {
                        result = r.RemoveAirport(AirportCode);
                        if (result > 0)
                        {
                            ViewBag.DeleteMessage = "airport details deleted !!";
                        }
                        else
                        {
                            ViewBag.DeleteError = "Not deleted";
                        }
                    }
                    return View();
                }
            }
            return RedirectToAction("Login", "User");
        }
       
    }
}

PMTGroup3/PMT.Presentation/Controllers/FlightController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PMT.DataAccess;
using PMT.Presentation.Models;

namespace PMT.Presentation.Controllers
{
   
    public class FlightController : Controller
    {
        
        // GET: Flight
        public ActionResult GetFlights()
        {
            if (Session["role"] != null)
            {
                if ((string)Session["role"] == "admin")
                {

                    Repository flight = new Repository();
                    List<Flight> flights = flight.GetFlights();
                    List<FlightModel> allflights = new List<FlightModel>();
                    foreach (Flight oldflight in flights)
                    {
                        FlightModel newflight = new FlightModel();
                        newflight.FlightName = oldflight.FlightName;
                        newflight.FlightNumber = oldflight.FlightNumber;
                        newflight.SeatsCapacity = oldflight.SeatsCapacity;
                        newflight.NoOfSeatsAvailable = oldflight.NoOfSeatsAvailable;
                        allflights.Add(newflight);
                    }
                    return View(allflights);
                }
            }
            return RedirectToAction("Login", "User");
        }
        public ActionResult AddFlights()
        {
            if (Session["role"] != null)
            {
                if ((string)Session["role"] == "admin")
                {
                    FlightModel emptyflight = new FlightModel();
                    return View(emptyflight);
                }
            }
            return RedirectToAction("Login", "User");
        }
        [HttpPost]
        public ActionResult AddFlights(FlightModel flight)
        {
            if (Session["role"] != null)
            {
                if ((string)Session["role"] == "admin")
                {
                    Repository allflights = new Repository();
                    Flight newflight = new Flight();
                    newflight.FlightName = flight.FlightName;
                    newflight.FlightNumber = flight.FlightNumber;
                    newflight.SeatsCapacity = flight.SeatsCapacity;
                    newflight.NoOfSeatsAvailable = flight.NoOfSeatsAvailable;
                    int result = 0;
                    if (ModelState.IsValid)
                    {
                        if (newflight.SeatsCapacity == newflight.NoOfSeatsAvailable)
                        {
                            result = allflights.AddFlight(newflight);
                            if (result == 1)
                            {
                                ViewBag.AddMessage = "Added Successfully";
                            }
                            else
                            {
                                ViewBag.ErrorMessage = "Attempt Unsuccessfull; Error: Please review the  requested action";
                            }
                        }
                        else
                        {
                            ViewBag.ErrorMessageEqual = "Seats Capacity and Available Seats must be same";
                        }
                    }
                    return View();
                }
            }
            return RedirectToAction("Login", "User");
        }
        public ActionResult UpdateFlight(String flightnumber)
        {
            if (Session["role"] != null)
            {
                if ((string)Session["role"] == "admin")
                {
                    Repository allflights = new Repository();
                    Flight findflight = allflights.GetFlight(flightnumber);
                    FlightModel flight = new FlightModel();
                    flight.FlightNumber = findflight.FlightNumber;
                    flight.FlightName = findflight.FlightName;
                    flight.SeatsCapacity = findflight.SeatsCapacity;
                    flight.NoOfSeatsAvailable = findflight.NoOfSeatsAvailable;
                    return View(flight);
                }
            }
            return RedirectToAction("Login", "User");
        }
        [HttpPost]
        public ActionResult UpdateFlight(FlightModel flight1)
        {
            if (Session["role"] != null)
            {
                if ((string)Session["role"] == "admin")
                {
                    Repository allflights = new Repository();
                    Flight updateflight = new Flight();
                    updateflight.FlightNumber = flight1.FlightNumber;
                    updateflight.FlightName = flight1.FlightName;
                    updateflight.SeatsCapacity = flight1.SeatsCapacity;
                    updateflight.NoOfSeatsAvailable = flight1.NoOfSeatsAvailable;
                    int result = 0;
                    if (ModelState.IsValid)
                    {
                        result = allflights.UpdateFlight(updateflight);
                        if (result == 1)
                        {
                            ViewBag.UpdateMessage = "Updated Successfully";
                        }
                        else
                        {
                            ViewBag.ErrorMessage = "Attempt Unsuccessfull; Error: Please review the  requested action";
                        }
                    }
                    return View();
                }
            }
            return RedirectToAction("Login", "User");
        }
        public ActionResult RemoveFlight(String flightnumber)
        {
            if (Session["role"] != null)
            {
                if ((string)Session["role"] == "admin")
                {
                    Repository allflights = new Repository();
                    Flight gotflight = allflights.GetFlight(flightnumber);
                    FlightModel model = new FlightModel();
                    model.FlightNumber = gotflight.FlightNumber;
                    model.FlightName = gotflight.FlightName;
                    model.SeatsCapacity = gotflight.SeatsCapacity;
                    model.NoOfSeatsAvailable = gotflight.NoOfSeatsAvailable;
                    return View(model);
                }
            }
            return RedirectToAction("Login", "User");
        }
        [HttpPost]
        [ActionName("RemoveFlight")]
        public ActionResult RemoveFlightPost(String flightnumber)
        {
            if (Session["role"] != null)
            {
                if ((string)Session["role"] == "admin")
                {
                    Repository allflights = new Repository();
                    int result = 0;

                    result = allflights.RemoveFlight(flightnumber);
                    if (result > 0)
                    {
                        ViewBag.RemoveMessage = "Removed Successfully";
                    }
                    else
                    {
                        ViewBag.ErrorMessage = "Attempt Unsuccessfull; Error: Please review the  requested action";
                    }

                    return View();
                }
            }
            return RedirectToAction("Login", "User");
        }   
    }
}

PMTGroup3/PMT.Presentation/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PMT.DataAccess;
using PMT.Presentation.Models;

namespace PMT.Presentation.Controllers
{
    public class UserController : Controller
    {
        public ActionResult ShowHome()
        {
            return View();
        }
        // GET: User
        public ActionResult Login()
        {
            LoginModel login = new LoginModel();
            return View(login);
        }

        [HttpPost]
        public ActionResult Login(LoginModel login)
        {
            Repository repository = new Repository();
            User user = new User();
            if (ModelState.IsValid)
            {
                user = repository.Login(login.EmailId, login.Password);
            }

            ViewBag.Msg = "";
            //ViewBag.viewname, viewbag.action

            if (user == null)
            {
                ViewBag.Msg = "Invalid username or password.";
              
            }
            else if (user.RoleId == 1)
            {
                Session["role"] = "admin";
                return RedirectToAction("ShowHome");
                
            }
            else if(user.RoleId==2)
            {
                Session["role"] = "user";
                return RedirectToAction("SearchFlights");
            }

           
            return View();  //user
        }

        public ActionResult Register()
        {
            UserModel model = new UserModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult Register(UserModel model)
        {
            Repository r = new Repository();
            User user = new User();
            user.FirstName = model.FirstName;
            user.LastName = model.LastName;
            user.EmailId = model.EmailId;
            user.Password = model.Password;
            user.RoleId = 2;

            if (ModelState.IsValid)
            {
                int result = r.Register(user);
                if (result == 1)
                {
                    ViewBag.Register = "User registered successfully!";
                }
            }
            return View();
        }

        

        public ActionResult SearchFlights()
        {
            if (Session["role"] != null)
            {
                if ((string)Session["role"] == "user")
                {
                    List<FlightScheduleModel> result = new List<FlightScheduleModel>();
                    return View(result);
                }
            }
            return RedirectToAction("Login");
        }

        [HttpPost]
        public ActionResult SearchFlights(string origin, string destination, string departure)
        {
            if (Session["role"] != null)
            {
                if ((string)Session["role"] == "user")
                {

                    DateTime departureDate = DateTime.Parse(departure);
                    Repository r = new Repository();
                    List<FlightSchedule> flights = new List<FlightSchedule>();

                    flights = r.SearchSchedule(origin, destination, departureDate.ToShortDateString());
                    List<FlightScheduleModel> result = new List<FlightScheduleModel>();
                    foreach (FlightSchedule f in flights)
                    {
                        FlightScheduleModel fl = new FlightScheduleModel();
                        fl.FlightNumber = f.FlightNumber;
                        fl.Origin = f.Airport1.Location;
                        fl.Destination = f.Airport.Location;
                        fl.DepartureTime = f.DepartureTime;
                        fl.ArrivalTime = f.ArrivalTime;
                        fl.AvailableSeats = f.Flight.NoOfSeatsAvailable;
                        result.Add(fl);
                    }
                    return View(result);
                }
            }
            return RedirectToAction("Login");
        }
    }
}

PMTGroup3/PMT.Presentation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>

    @*@Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")*@
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Plan My Trip</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <link href="http://fonts.googleapis.com/css?family=Karla:400,700" rel="stylesheet">
    <link href="~/Content/default.css" rel="stylesheet" type="text/css" media="all">
    <link href="~/Content/fonts.css" rel="stylesheet" type="text/css" media="all">
    @Styles.Render("~/Content/jqueryui")
</head>
<body>
    <div id="wrapper">
        <div id="header-wrapper">
            <div id="header" class="container">
                @*<div id="banner"> <a ref="#" class="image"><img src="~/Content/images/Flight3.jpg" alt=""></a> </div>*@
                <div id="logo">
                    @*<h1>Plan My Trip</h1>
                        <div>

                            <p>Design by Praveen Kumar</a></p>

                        </div>*@
                </div>

            </div>
        </div>
        <div id="menu-wrapper">
            <div id="menu" class="container">

                <ul>
                    <li class="current_page_item">
                        @Html.ActionLink("Home Page", "ShowHome", "User")
                    </li>

                    @{ 
                        if (Session["role"] != null)
                        {
                            if ((string)Session["role"] == "admin")
                            {
                    <li> @Html.ActionLink("Flight Admin", "GetFlights", "Flight")</li>
                    <li> @Html.ActionLink("Airport Admin", "GetAirport", "Airport")</li>
                    <li> @Html.ActionLink("Flight Schedules Admin", "FlightSchedules", "FlightSchedule")</li>
                            }
                        }
                        }

                </ul>

            </div>
            <!-- end #menu -->
        </div>


        <div class="title">

            <h1>

                Plan your trip with us to make it the best
            </h1>

            <div class="SignUpPara">

                <p style="text-align:justify">
                    <a href="#">@Html.ActionLink("Sign up", "Register", "User")</a>|

                    <a href="#">@Html.ActionLink("Login", "Login", "User")</a>
                </p>
            </div>




        </div>
        <div id="sidebar">
            <div class="">
                <ul class="style2">
                    @{ 
                        if (Session["role"] != null)
                        {

                            if ((string)Session["role"] == "user")
                            {
                        @Html.ActionLink("Search Flights", "SearchFlights", "User")
                                }
                            }
                        }
                </ul>
            </div>
        </div>
    </div>
    @*</div>*@
    <div class="container">
        @RenderBody()

    </div>
    <hr />
    <footer>
        <div id="copyright" class="container">
            <p>© Untitled. All rights reserved. |  Design by Praveen Kumar - Software Developer.</p>
        </div>
    </footer>
    @*<div id="footer-wrapper">
            <div id="footer" class="container">
                <div id="box1">
                    <div class="title">
                        <h2>Latest Post</h2>
                    </div>
                    <ul class="style1">
                        <li><a href="#">Semper mod quis eget mi dolore</a></li>
                        <li><a href="#">Quam turpis feugiat sit dolor</a></li>
                        <li><a href="#">Amet ornare in hendrerit in lectus</a></li>
                        <li><a href="#">Consequat etiam lorem phasellus</a></li>
                        <li><a href="#">Amet turpis, feugiat et sit amet</a></li>
                        <li><a href="#">Semper mod quisturpis nisi</a></li>
                    </ul>
                </div>
                <div id="box2">
                    <div class="title">
                        <h2>Popular Links</h2>
                    </div>
                    <ul class="style1">
                        <li><a href="#">Semper mod quis eget mi dolore</a></li>
                        <li><a href="#">Quam turpis feugiat sit dolor</a></li>
                        <li><a href="#">Amet ornare in hendrerit in lectus</a></li>
                        <li><a href="#">Consequat etiam lorem phasellus</a></li>
                        <li><a href="#">Amet turpis, feugiat et sit amet</a></li>
                        <li><a href="#">Semper mod quisturpis nisi</a></li>
                    </ul>
                </div>
                <div id="box3">
                    <div class="title">
                        <h2>Follow Us</h2>
                    </div>
                    <p>Proin eu wisi suscipit nulla suscipit interdum. Aenean lectus lorem, imperdiet magna.</p>
                    <ul class="contact">
                        <li><a href="#" class="icon icon-twitter"><span>Twitter</span></a></li>
                        <li><a href="#" class="icon icon-facebook"><span>Facebook</span></a></li>
                        <li><a href="#" class="icon icon-dribbble"><span>Dribbble</span></a></li>
                        <li><a href="#" class="icon icon-tumblr"><span>Tumblr</span></a></li>
                        <li><a href="#" class="icon icon-rss"><span>Pinterest</span></a></li>
                    </ul>
                    <a href="#" class="icon icon-plus-sign button">Read More</a>
                </div>
            </div>
        </div>*@


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    @Scripts.Render("~/bundles/jqueryval")
    @RenderSection("scripts", required: false)
    @Scripts.Render("~/bundles/jqueryui")
    <script type="text/javascript">
        $(document).ready(function () {
            $('.datetimepicker').datepicker({
                dateFormat: "dd-mm-yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "-60:+0"
            });
        });
    </script>
</body>
</html>

PMTGroup3/PMT.Presentation/Views/Shared/_PMTLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>